### ISSUE TITLE
Crab has `none` health causing exceptions in battle

### ISSUE THREAD

**Issue by alexdriedger** [manny405/sapai#13]
I have not been able to recreate this exception with a small test yet, but I will update with a minimal unit tests to recreate it once I figure that out. 

The exception is caused by a Crab with `none` health. This causes an exception when battling another team.

This was the final action before the battle

```
('buy_pet',
  [{'ability_counter': 0,
    'attack': 3,
    'eaten': False,
    'experience': 0,
    'health': 'none',
    'level': 1,
    'name': 'pet-crab',
    'override_ability': False,
    'override_ability_dict': {},
    'player': {},
    'seed_state': None,
    'shop': {},
    'status': 'none',
    'team': {},
    'type': 'Pet'}])
```

```
CURRENT TEAM: 
--------------
0: < Slot pet-crab 3-none none 1-0 > 
    1: < Slot EMPTY > 
    2: < Slot pet-elephant 4-5 none 1-0 > 
    3: < Slot EMPTY > 
    4: < Slot EMPTY > 
    
CURRENT SHOP: 
--------------
0: < ShopSlot-pet not-frozen 3-gold pet-mosquito 2-2 none 1-0 > 
    1: < ShopSlot-pet not-frozen 3-gold pet-elephant 3-5 none 1-0 > 
    2: < ShopSlot-food not-frozen 3-gold food-honey 0-0 status-honey-bee > 
```

```
Traceback (most recent call last):
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\battle.py", line 69, in battle
    self.start()
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\battle.py", line 105, in start
    battle_phase(self,
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\battle.py", line 394, in battle_phase
    battle_phase_hurt_and_faint(battle_obj,phase,teams,pet_priority,phase_dict)
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\battle.py", line 515, in battle_phase_hurt_and_faint
    if p.health <= 0:
TypeError: '<=' not supported between instances of 'str' and 'int'
```

**Comment by manny405** [comment]
It seems this has to do with the crab being added ahead of the elephant (or other team members). A minimal test to reproduce is as follows

```py
from sapai import Shop, Player, Team, Pet, Battle
from sapai.shop import ShopSlot,ShopLearn
from sapai.teams import TeamSlot

sl = ShopLearn(turn=3)
p = Player(team=[TeamSlot(), TeamSlot(), "dragon"],
           shop=sl)
print(sl[9])
p.buy_pet(9)
print(p.team)
```

```
< ShopSlot-pet not-frozen 3-gold pet-crab 3-3 none 1-0 >
0: < Slot pet-crab 3-none none 1-0 > 
    1: < Slot EMPTY > 
    2: < Slot pet-dragon 6-8 none 1-0 > 
    3: < Slot EMPTY > 
    4: < Slot EMPTY > 
```

I'll work on tracking down the reason for this now.
