### ISSUE TITLE
Tiger func throwing exception (No tigers involved)

### ISSUE THREAD

**Issue by alexdriedger** [manny405/sapai#14]
### Battle Exception
```py
from sapai import Team, Pet, Battle

team1 = Team([Pet("fish")])
team2 = Team([Pet("whale"), Pet("hedgehog"), Pet("fish"), Pet("rabbit")])

battle = Battle(team1, team2)
battle.battle()
```

```
Traceback (most recent call last):
  File "C:\Users\aldri\Projects\super-auto-ai\test_stuff.py", line 66, in <module>
    battle.battle()
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\battle.py", line 69, in battle
    self.start()
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\battle.py", line 105, in start
    battle_phase(self,
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\battle.py", line 380, in battle_phase
    battle_phase_start(battle_obj,phase,teams,pet_priority,phase_dict)
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\battle.py", line 496, in battle_phase_start
    activated,targets,possible = p.sob_trigger(oteam)
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\pets.py", line 566, in sob_trigger
    targets,possible = tiger_func(
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\pets.py", line 856, in tiger_func
    targets,possible = func(*args)
ValueError: not enough values to unpack (expected 2, got 0)
```

### Shop Exception
Additionally, I have seen this exception as well from the tiger function. This exception occurred in the shop
  ```
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\player.py", line 13, in store_action
    targets = func(*args,**kwargs)
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\player.py", line 152, in buy_pet
    slot._pet.friend_summoned_trigger(pet)
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\pets.py", line 372, in friend_summoned_trigger
    targets,possible = tiger_func(
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\pets.py", line 856, in tiger_func
    targets,possible = func(*args)
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\effects.py", line 615, in ModifyStats
    target,possible = get_target(apet, apet_idx, teams, te=te)
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\effects.py", line 174, in get_target
    if temp_slot.pet.health > 0:
TypeError: '>' not supported between instances of 'str' and 'int'
  ```

**Comment by manny405** [comment]
The tiger_func is called for all pet abilities in battles. It should probably be renamed to  check_tiger_func, or any other better suggestion. It serves as a wrapper to handle if a tiger is behind an animal whose ability has been activated in battle. So, it's always being called whether a tiger is present or not. 

The first issue is because an exit condition in the ``Swallow`` implementation was returning one empty list instead of two, where two is required by the API standard. That has been corrected in most recent PR. 

The other error I cannot speak to yet.
