### ISSUE TITLE
Cat throws exception in battle

### ISSUE THREAD

**Issue by alexdriedger** [manny405/sapai#18]
Here's a simple case to reproduce the bug.

```py
    def test_cat_battle(self):
        team1 = Team([Pet("fish")])
        team2 = Team([Pet("cat")])

        test_battle = Battle(team1, team2)
        test_battle.battle()
```

```
Traceback (most recent call last):
  File "C:\Users\aldri\Projects\sapai-fork\tests\test_battles.py", line 70, in test_tiger_func_food_multiplier_exception_cat
    test_battle.battle()
  File "C:\Users\aldri\Projects\sapai-fork\sapai\battle.py", line 76, in battle
    result = self.attack(battle_iter)
  File "C:\Users\aldri\Projects\sapai-fork\sapai\battle.py", line 172, in attack
    battle_phase(
  File "C:\Users\aldri\Projects\sapai-fork\sapai\battle.py", line 394, in battle_phase
    battle_phase_hurt_and_faint(battle_obj,phase,teams,pet_priority,phase_dict)
  File "C:\Users\aldri\Projects\sapai-fork\sapai\battle.py", line 592, in battle_phase_hurt_and_faint
    activated,targets,possible = p.hurt_trigger(trigger=oteam)
  File "C:\Users\aldri\Projects\sapai-fork\sapai\pets.py", line 699, in hurt_trigger
    targets,possible = tiger_func(
  File "C:\Users\aldri\Projects\sapai-fork\sapai\pets.py", line 857, in tiger_func
    targets,possible = func(*args)
  File "C:\Users\aldri\Projects\sapai-fork\sapai\effects.py", line 597, in FoodMultiplier
    if food.attack == food.base_attack:
AttributeError: 'Team' object has no attribute 'attack'
```

It looks like the cat's trigger is set to `Hurt`, which is causing it to be triggered in battle. I believe that `EatsShopFood` would be the correct trigger.

https://github.com/manny405/sapai/blob/58d65a77c1668d590cacbec0cdb3b81dcb664e74/sapai/data.py#L10379

**Comment by manny405** [comment]
I see. I've updated data.py in the main branch. 

I changed the trigger to PurchaseFood. The test is now passing. PurchaseFood is a new trigger and won't overlap with any others because the cat's trigger always needs to be called first. 

The cat's ability is handled separately of all others, so this change will not impact the cat's ability behavior.

**Comment by alexdriedger** [comment]
Fantastic. Also, as a side note, I'll push my repo soon that has an "Arena" that starts a bunch of players, does their shop phases, then pairs them up in battles. The shop phases are completely random which is how I've found all the exceptions. It would probably be helpful for smoothing out the rest of the exceptions from battles

**Comment by manny405** [comment]
Great! Your testing has been an excellent help! 

I've been working a workflow via MongoDB to perform completely asynchronous player creation and team battling. The database infrastructure is built but I've been having trouble deciding how to search the space efficiently and effectively...
