### ISSUE TITLE
Parrot behind whale raising exception

### ISSUE THREAD

**Issue by alexdriedger** [manny405/sapai#25]
https://github.com/manny405/sapai/blob/aa44e10f504a4feae4594d6df925c3f39a23c767/sapai/effects.py#L896-L897

Unfortunately, I couldn't figure out how to reproduce it in a unit test, but having a parrot behind a whale will sometimes raise an exception. The pet name when the exception is raised is "pet-parrot"

```
Traceback (most recent call last):
  File "C:\Users\aldri\Projects\super-auto-ai\Arena.py", line 135, in battle_phase_all_players
    raise e
  File "C:\Users\aldri\Projects\super-auto-ai\Arena.py", line 120, in battle_phase_all_players
    self.do_battle_phase(game_state_id_1, game_state_id_2)
  File "C:\Users\aldri\Projects\super-auto-ai\Arena.py", line 82, in do_battle_phase
    winner = battle.battle()
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\battle.py", line 69, in battle
    self.start()
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\battle.py", line 105, in start
    battle_phase(self,
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\battle.py", line 380, in battle_phase
    battle_phase_start(battle_obj,phase,teams,pet_priority,phase_dict)
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\battle.py", line 496, in battle_phase_start
    activated,targets,possible = p.sob_trigger(oteam)
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\pets.py", line 566, in sob_trigger
    targets,possible = tiger_func(
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\pets.py", line 857, in tiger_func
    targets,possible = func(*args)
  File "C:\Users\aldri\Projects\super-auto-ai\venv\lib\site-packages\sapai\effects.py", line 897, in Swallow
    raise Exception("Swallow only done by whale")
Exception: Swallow only done by whale
```

**Comment by alexdriedger** [comment]
Here's an example to reproduce it. The part I was missing was that the player has to end their turn so that the parrot gets the whale's ability

```py
def test_whale_parrot_swallow(self):
    team1 = Team([Pet("whale"), Pet("parrot")])
    team2 = Team([Pet("fish")])

    player1 = Player(team=team1)
    player2 = Player(team=team2)

    player1.end_turn()
    player2.end_turn()

    test_battle = Battle(player1.team, player2.team)
    test_battle.battle()
```

**Comment by manny405** [comment]
Corrected and test added. Also, the battle graph below shows that the parrot correctly spits out the whale upon fainting. 

``` py
from sapai import Team, Pet, Battle, Player
from sapai.graph import graph_battle

team1 = Team([Pet("whale"), Pet("parrot")])
team2 = Team([Pet("fish"), "dragon"])

player1 = Player(team=team1)
player2 = Player(team=team2)

player1.end_turn()
player2.end_turn()

test_battle = Battle(player1.team, player2.team)
test_battle.battle()

graph_battle(test_battle, "parrow_whale")
```

![image](https://github.com/manny405/sapai/files/8003334/parrow_whale_correct.pdf)
