### ISSUE TITLE
Scorpion combine raises exception

### ISSUE THREAD

**Issue by alexdriedger** [manny405/sapai#28]
https://github.com/manny405/sapai/blob/f650ea7c0e09184f8b927549fceb0f79a9102f9b/sapai/player.py#L496-L503

Scorpion's `status-poison-attack` isn't in the status dictionary, causing an exception when combining scorpions. I'm not sure which tier it belongs in in order to resolve correctly

```py
def test_combine_scorpions(self):
    player = Player(team=["scorpion", "scorpion"])
    player.combine(0, 1)
```
```
Traceback (most recent call last):
  File "C:\Users\aldri\Projects\sapai-fork\tests\test_player.py", line 96, in test_combine_scorpions
    player.combine(0, 1)
  File "C:\Users\aldri\Projects\sapai-fork\sapai\player.py", line 13, in store_action
    targets = func(*args,**kwargs)
  File "C:\Users\aldri\Projects\sapai-fork\sapai\player.py", line 392, in combine
    cstatus = get_combined_status(pet1,pet2)
  File "C:\Users\aldri\Projects\sapai-fork\sapai\player.py", line 511, in get_combined_status
    max_idx = np.argmax([status_lookup[pet1.status],
KeyError: 'status-poison-attack'
```

**Comment by manny405** [comment]
Probably tier-0 because it will be overriden by everything upon combination (unless I am wrong about that). 

Also, I'm noticing I had status-extra-life in tier-0 and tier-5. It should be removed from tier-0 and only be in tier-5.
